services:
  - type: web
    name: health-monitor-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FIREBASE_PROJECT_ID
        value: newnod-4933c
      - key: FIREBASE_PRIVATE_KEY_ID
        value: c41810fca24f71ca01b4a819760e0c4ab3591285
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-pxbd3@newnod-4933c.iam.gserviceaccount.com
      - key: SECRET_KEY
        generateValue: true
    repo: https://github.com/Harikriznen/health-monitor-app
